---
#
# Playbook to Check status of Three-tier Application EC2 instances
#

- hosts: tag_instance_filter_three_tier_app_rdurvas1_in_ibm_com
  gather_facts: false
  tasks:

  - name: Check the instances status
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
#    delegate_to: localhost
    delegate_to: "{{groups['tag_AnsibleGroup_bastions'][0]}}"
    with_items:
      - "{{ inventory_hostname }}"
        
