---
#
# Playbook to setup workstation and create osp network, router, SG and ssh keypair
#

- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation
  - name: Copy cloud-user ssh key
    copy:
      src: /root/.ssh/openstack.pem
      dest: /home/cloud-user/.ssh/
      mode: 0400

- hosts: workstation
  become: yes
  roles:
    - setup-workstation

- import_playbook: site-install-isolated-node.yml 

