---

- name: Playbook to operate on tower
  hosts: localhost
  become: yes
  vars_files:
    - roles/config-tower/vars/main.yml

  tasks:
#    - name: Create vault credentials for project.repo
#      command: |
#        tower-cli credential create --name="project-repo-cred" --organization "{{org_name}}" --inputs='{"vault_password":"passw0rd"}' --credential-type="Vault"

    - name: List key files
      shell: (cd /root/.ssh; find . -maxdepth 1 -type f -iname '*key.pem')| cut -d'/' -f2
      register: file_to_copy
    - name: Read PEM file
      set_fact:
        local_priv_key: "{{ lookup('file', '/root/.ssh/{{file_to_copy.stdout}}') }}"
    - name: Print local_priv_key content
      debug:
        msg: "{{local_priv_key}}"

