---
# tasks file for base-config
#
# Purpose: Install common OS packages on servers
#

- name: enable yum repos
  copy:
    src: files/project.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644
    decrypt: yes
